#!/bin/sh
export CC="/opt/trimui-toolchain/bin/arm-linux-gcc"
export CFLAGS="-Os -flto"
export LDFLAGS="-Wl,--gc-sections"
./configure --host=arm-buildroot-linux-gnueabi\
 --enable-alsa=no\
 --enable-alsa-shared=no\
 --enable-esd=no\
 --enable-esd-shared=no\
 --enable-sndio=no\
 --enable-pulseaudio=no\
 --enable-pulseaudio-shared=no\
 --enable-arts=no\
 --enable-arts-shared=no\
 --enable-nas=no\
 --enable-nas-shared=no\
 --enable-diskaudio=no\
 --enable-dummyaudio=no\
 --enable-mintaudio=no\
 --enable-nasm=no\
 --enable-altivec=no\
 --enable-video-x11=no\
 --enable-x11-shared=no\
 --enable-dga=no\
 --enable-video-dga=no\
 --enable-video-x11-dgamouse=no\
 --enable-video-x11-vm=no\
 --enable-video-x11-xv=no\
 --enable-video-x11-xinerama=no\
 --enable-video-x11-xme=no\
 --enable-video-x11-xrandr=no\
 --enable-video-photon=no\
 --enable-video-cocoa=no\
 --enable-video-directfb=no\
 --enable-video-ps2gs=no\
 --enable-video-ps3=no\
 --enable-video-svga=no\
 --enable-video-vgl=no\
 --enable-video-wscons=no\
 --enable-xbios=no\
 --enable-gem=no\
 --enable-video-dummy=no\
 --enable-osmesa-shared=no\
 --enable-input-tslib=no\
 --enable-stdio-redirect=no\
 --enable-directx=no\
 --enable-atari-ldg=no
